version: "3"
services: 
  postgres:
    image: postgres
    container_name: local_postgresql
    restart: always
    environment:
      POSTGRES_DB: callsysdb
      POSTGRES_USER: callsys
      POSTGRES_PASSWORD: bupt2017
    ports:
        - 5432:5432
    volumes:
      - /data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis:4.0.8-alpine
      container_name: db-redis
      restart: always
      ports:
        - 6379:6379
      networks:
        - net_db
      command: redis-server /docker/config/redis.conf